# For interactive development.
env: dev

database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/test?loggerLevel=OFF"
  username: "test"
  password: "test"
  maximumPoolSize: 1

server:
  host: 0.0.0.0.0
  port: 8080
  # The working directory will be different (by default) depending on whether it is run from Gradle or IDEA.
  static: "browser/build/distributions/"
